# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/ep08_-_ALU/comp.xdc

# Block Designs: bd/cga_bold_rom_reduced/cga_bold_rom_reduced.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cga_bold_rom_reduced || ORIG_REF_NAME==cga_bold_rom_reduced} -quiet] -quiet

# IP: bd/cga_bold_rom_reduced/ip/cga_bold_rom_reduced_blk_mem_gen_0_0/cga_bold_rom_reduced_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cga_bold_rom_reduced_blk_mem_gen_0_0 || ORIG_REF_NAME==cga_bold_rom_reduced_blk_mem_gen_0_0} -quiet] -quiet

# XDC: bd/cga_bold_rom_reduced/cga_bold_rom_reduced_ooc.xdc
