# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/xilinx/Downloads/Multicomp/zedmulti/zedmulti.cache/wt [current_project]
set_property parent.project_path D:/xilinx/Downloads/Multicomp/zedmulti/zedmulti.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zedboard:part0:1.0 [current_project]
set_property ip_repo_paths d:/xilinx/Downloads/xilinxmulti/xilinxmulti.srcs/sources_1/bd/cga_bold_rom_reduced/ip [current_project]
update_ip_catalog
set_property ip_output_repo d:/xilinx/Downloads/Multicomp/zedmulti/zedmulti.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files d:/downloads/multicompcpm-papilioduocs-jlc/ROMS/BMON/CGAFontBoldReduced.coe
read_vhdl -library xil_defaultlib {
  D:/xilinx/Downloads/Multicomp/Components/M6502/T65_Pack.vhd
  D:/xilinx/Downloads/Multicomp/Components/M6502/T65.vhd
  D:/xilinx/Downloads/Multicomp/Components/M6502/T65_ALU.vhd
  D:/xilinx/Downloads/Multicomp/Components/M6502/T65_MCode.vhd
  D:/xilinx/Downloads/Multicomp/zedmulti/zedmulti.srcs/sources_1/bd/cga_bold_rom_reduced/hdl/cga_bold_rom_reduced_wrapper.vhd
  D:/xilinx/Downloads/Multicomp/zedmulti/zedmulti.srcs/sources_1/imports/fpga/clk.vhd
}
read_vhdl -vhdl2008 -library xil_defaultlib {
  D:/xilinx/Downloads/Multicomp/zedmulti/zedmulti.srcs/sources_1/imports/mem/rom.vhd
  D:/xilinx/Downloads/Multicomp/zedmulti/zedmulti.srcs/sources_1/imports/mem/ram.vhd
  D:/xilinx/Downloads/Multicomp/zedmulti/zedmulti.srcs/sources_1/imports/mem/dmem.vhd
  D:/xilinx/Downloads/Multicomp/zedmulti/zedmulti.srcs/sources_1/imports/TERMINAL/SBCTextDisplayRGB.vhd
  D:/xilinx/Downloads/Multicomp/zedmulti/zedmulti.srcs/sources_1/imports/Microcomputer/Microcomputer.vhd
  D:/xilinx/Downloads/Multicomp/zedmulti/zedmulti.srcs/sources_1/new/multicomp_wrapper.vhd
}
add_files D:/xilinx/Downloads/Multicomp/zedmulti/zedmulti.srcs/sources_1/bd/cga_bold_rom_reduced/cga_bold_rom_reduced.bd
set_property used_in_implementation false [get_files -all d:/xilinx/Downloads/Multicomp/zedmulti/zedmulti.srcs/sources_1/bd/cga_bold_rom_reduced/ip/cga_bold_rom_reduced_blk_mem_gen_0_0/cga_bold_rom_reduced_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/xilinx/Downloads/Multicomp/zedmulti/zedmulti.srcs/sources_1/bd/cga_bold_rom_reduced/cga_bold_rom_reduced_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/xilinx/Downloads/Multicomp/zedmulti/zedmulti.srcs/constrs_1/imports/ep08_-_ALU/comp.xdc
set_property used_in_implementation false [get_files D:/xilinx/Downloads/Multicomp/zedmulti/zedmulti.srcs/constrs_1/imports/ep08_-_ALU/comp.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top multicomp_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef multicomp_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file multicomp_wrapper_utilization_synth.rpt -pb multicomp_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
